/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2018-12-22 08:17:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Container_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write('\r');
      out.write('\n');

	String selected_page = request.getParameter("selected_page");
	
	if(selected_page == null){
		pageContext.include("Main.jsp");
	}
	else if(selected_page.equals("today")){
		pageContext.include("Map.jsp");
	}
	else if(selected_page.equals("login")){
		pageContext.include("Login.jsp");
	}
	else if(selected_page.equals("join")){
		pageContext.include("Join.jsp");
	}
	else if(selected_page.equals("notice")){
		if(request.getParameter("page_number") == null )
			pageContext.include("Board.jsp?category=notice");
		else
			pageContext.include("Board.jsp?category=notice&page_number="+request.getParameter("page_number"));
	}
	else if(selected_page.equals("qna")){
		if(request.getParameter("page_number") == null )
			pageContext.include("Board.jsp?category=qna");
		else
			pageContext.include("Board.jsp?category=qna&page_number="+request.getParameter("page_number"));
	}
	else if(selected_page.equals("music")){
		if(request.getParameter("page_number") == null )
			pageContext.include("Music.jsp");
		else
			pageContext.include("Music.jsp?page_number="+request.getParameter("page_number"));
	}
	else if(selected_page.equals("notice_write")){
		pageContext.include("Notice_write.jsp");
	}
	else if(selected_page.equals("notice_read")){
		pageContext.include("Notice_read.jsp?article_number=" + request.getParameter("article_number"));
	}
	else if(selected_page.equals("notice_update")){
		pageContext.include("Notice_update.jsp?article_number=" + request.getParameter("article_number"));
	}
	else if(selected_page.equals("qna_write")){
		pageContext.include("Qna_wirte.jsp");
	}
	else if(selected_page.equals("qna_read")){
		pageContext.include("Qna_read.jsp?article_number=" + request.getParameter("article_number"));
	}
	else if(selected_page.equals("qna_update")){
		pageContext.include("Qna_update.jsp?article_number=" + request.getParameter("article_number"));
	}
	else if(selected_page.equals("music_manager")){
		if(request.getParameter("page_number") == null)
			pageContext.include("Board.jsp?category=music_manager");
		else 
			pageContext.include("Board.jsp?category=music_manager&page_number=" + request.getParameter("page_number"));		
	}	
	else if(selected_page.equals("music_read")){
		pageContext.include("Music_read.jsp?article_number=" + request.getParameter("article_number"));
	}
	else if(selected_page.equals("music_write")){
		pageContext.include("Music_write.jsp");
	}
	else if(selected_page.equals("music_update")){
		pageContext.include("Music_update.jsp?article_number=" + request.getParameter("article_number"));
	}
	else if(selected_page.equals("survey")){
		pageContext.include("Survey.jsp");
	}
	else if(selected_page.equals("mypage")){
		pageContext.include("Mypage.jsp");
	}
	else if(selected_page.equals("management")){
		if(request.getParameter("page_number") == null)
			pageContext.include("Management.jsp");
		else if(request.getParameter("id") != null)
			pageContext.include("Management.jsp?id=" + request.getParameter("id"));
		
		else 
			pageContext.include("Management.jsp?page_number=" + request.getParameter("page_number"));		
	}	
	else if(selected_page.equals("management_update")){
		pageContext.include("Management_update.jsp?id=" + request.getParameter("id"));
	}
	else if(selected_page.equals("healthcare_food")){
		pageContext.include("Healthcare_Food.jsp");
	}
	else if(selected_page.equals("healthcare_stretching")){
		pageContext.include("Healthcare_Stretching.jsp");
	}
	else if(selected_page.equals("healthcare_news")){
		pageContext.include("HealthNews.jsp");
	}

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.html", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
