/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2018-12-16 07:47:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("width:1080px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#header{\r\n");
      out.write("width:1080px;\r\n");
      out.write("height:28px;\r\n");
      out.write("background:#FFEAEA;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#Loheader{\r\n");
      out.write("width:230px;\r\n");
      out.write("float:right;\r\n");
      out.write("heigth:28px;\r\n");
      out.write("background: #FFEAEA;\r\n");
      out.write("margin:80px 0px 0px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#log{\r\n");
      out.write("float:right;\r\n");
      out.write("width:230px;\r\n");
      out.write("line-height: 1.7em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#log a {\r\n");
      out.write("font-size:16px;\r\n");
      out.write("color: black;\r\n");
      out.write("text-decoration:none; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#log a:hover {\r\n");
      out.write("text-decoration:underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#mainlogo{\r\n");
      out.write("width:1080px;\r\n");
      out.write("background:;\r\n");
      out.write("}\r\n");
      out.write("#mainlogo img{\r\n");
      out.write("margin:0px 0px 0px 300px;\r\n");
      out.write("}\r\n");
      out.write("#nav{\r\n");
      out.write("width:1080px;\r\n");
      out.write("height:180px;\r\n");
      out.write("}\r\n");
      out.write("#logo{\r\n");
      out.write("float:left;\r\n");
      out.write("width:1080px;\r\n");
      out.write("background:#FFEAEA;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#search{\r\n");
      out.write("width:750px;\r\n");
      out.write("height:100px;\r\n");
      out.write("float:right;\r\n");
      out.write("background:red;\t\r\n");
      out.write("}\r\n");
      out.write("#TM{\r\n");
      out.write("width:1080px;\r\n");
      out.write("height:60px;\r\n");
      out.write("border-top:1px solid red; border-bottom:1px solid red; \r\n");
      out.write("font-size:25px;\r\n");
      out.write("text-align:center;\r\n");
      out.write("margin:10px 0px 10px 0px;\r\n");
      out.write("line-height: 1.6em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#TM ul {\r\n");
      out.write("   list-style: none;\r\n");
      out.write("   padding:0px 0;\r\n");
      out.write("   margin: 0px;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("#TM ul li {\r\n");
      out.write("   float : left;\r\n");
      out.write("   line-height : 2.5em;\r\n");
      out.write("   position : relative;\r\n");
      out.write("   width:150px;\r\n");
      out.write("   padding: 0px 15px 0px 15px;\r\n");
      out.write("}  \r\n");
      out.write("\r\n");
      out.write(".menuLink { \r\n");
      out.write("   text-decoration:none;\r\n");
      out.write("   display: block;\r\n");
      out.write("   width: 150px;\r\n");
      out.write("   color:black;\r\n");
      out.write("}\r\n");
      out.write(".submenu {\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   display:none;\r\n");
      out.write("   overflow:hidden;\r\n");
      out.write("   background-color:black;\r\n");
      out.write("\topacity:0.7;\r\n");
      out.write("\tfont-size:15px;\r\n");
      out.write("}\r\n");
      out.write(".topmenu:hover .submenu{\r\n");
      out.write("   display:block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submenu a {\r\n");
      out.write("   text-decoration : none;\r\n");
      out.write("   color : white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=mainlogo>\r\n");
      out.write("<a href=\"Container.jsp\"><img src=\"img/logoLast.PNG\" width=450 height=100/></a>\r\n");
      out.write("<div id=Loheader>\r\n");

	if(session.getAttribute("id") == null){
		out.println("<div id=log><a href='Container.jsp?selected_page=login'>LOGIN</a><span> | </span><a href='Container.jsp?selected_page=join'>JOIN</a><span> | </span><a href='Container.jsp?selected_page=mypage'>MYPAGE</a></div>"); // MYPAGE는 삭제가 필요함.
	}
	else{
		out.println("<div id=log><a href='Container.jsp?selected_page=management'>" + session.getAttribute("name") + " 님" + "</a><span> | </span><a href='Logout.jsp'>LOGOUT</a><span> | </span><a href='Container.jsp?selected_page=mypage'>MYPAGE</a></div>");
	}	

      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id = TM>\r\n");
      out.write("<ul>\r\n");
      out.write("<li>&nbsp</li>\r\n");
      out.write(" <li class=\"topmenu\"><a class=\"menuLink\" href=\"Container.jsp?selected_page=today\">오늘의 건강</a>\r\n");
      out.write(" \t<!-- <ul class=\"submenu\">\r\n");
      out.write("     <li class=\"submenuLink\"><a href=\"#\">식습관 생활</a></li>\r\n");
      out.write("     <li class=\"submenuLink\"><a href=\"#\">생활 습관</a></li>\r\n");
      out.write("     <li class=\"submenuLink\"><a href=\"#\">추천 음악</a></li>\r\n");
      out.write("   </ul> -->\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class=\"topmenu\"><a class=\"menuLink\" href=\"Container.jsp?selected_page=survey\">건강설문</a>\r\n");
      out.write("   <!-- <ul class=\"submenu\">\r\n");
      out.write("     <li class=\"submenuLink\"><a href=\"#\">알코올 자가진단</a></li>\r\n");
      out.write("     <li class=\"submenuLink\"><a href=\"#\">흡연 자가진단</a></li>\r\n");
      out.write("     <li class=\"submenuLink\"><a href=\"#\">스마트폰 자가진단</a></li>\r\n");
      out.write("   </ul> -->\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class=\"topmenu\"><a class=\"menuLink\" href=\"Container.jsp?selected_page=healthcare_food\">헬스케어</a>\r\n");
      out.write("   <ul class=\"submenu\">\r\n");
      out.write("     <li class=\"submenuLink\"><a href=\"Container.jsp?selected_page=healthcare_food\">추천 건강푸드</a></li>\r\n");
      out.write("     <li class=\"submenuLink\"><a href=\"Container.jsp?selected_page=healthcare_stretching\">스트레칭</a></li>\r\n");
      out.write("     <li class=\"submenuLink\"><a href=\"Container.jsp?selected_page=music\">추천음악</a></li>\r\n");
      out.write("   </ul>\r\n");
      out.write("</li>\r\n");
      out.write(" <li class=\"topmenu\"><a class=\"menuLink\" href=\"Container.jsp?selected_page=healthcare_news\">자료실</a>\r\n");
      out.write(" \t<ul class=\"submenu\">\r\n");
      out.write("     <li class=\"submenuLink\"><a href=\"Container.jsp?selected_page=healthcare_news\">건강신문</a></li>\r\n");
      out.write("   </ul>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class=\"topmenu\"><a class=\"menuLink\" href=\"Container.jsp?selected_page=notice\">커뮤니티</a>\r\n");
      out.write("  <ul class=\"submenu\">\r\n");
      out.write("   <li class=\"submenuLink\"><a href=\"Container.jsp?selected_page=notice\">공지사항</a></li>\r\n");
      out.write("   <li class=\"submenuLink\"><a href=\"Container.jsp?selected_page=qna\">Q&A</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- \r\n");
      out.write("<div id=nav>\r\n");
      out.write("<div id=logo><a href=\"Container.jsp\"><img src=\"img/logo.PNG\" width=250 height=170/></a>\r\n");
      out.write("</div>-->\r\n");
      out.write("<!-- <p style='line-height : 0.6em;'>&nbsp</p> -->\r\n");
      out.write("<!-- <div id=search></div> -->\r\n");
      out.write("<!-- <div id = search><p>연관검색어 | 하루식단   스트레칭   자료실   추천도서   알코올자가진단   맞춤영양식단</p>\r\n");
      out.write("<input type=\"text\" size=80> <input type=\"button\" value=\"검색\"></div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
