/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2018-12-16 07:48:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Healthcare_005fStretching_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("width:1080px;\r\n");
      out.write("text-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#aside{\r\n");
      out.write("height:100px;\r\n");
      out.write("width:180px;\r\n");
      out.write("font-size:28px;\r\n");
      out.write("background: #FF9595;\r\n");
      out.write("float:left;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("#stretcontent{\r\n");
      out.write("width:900px;\r\n");
      out.write("background: #FFEAEA;\r\n");
      out.write("float:right;\r\n");
      out.write("heigth:;\r\n");
      out.write("}\r\n");
      out.write("#stretcontent table{\r\n");
      out.write("margin:0px 0px 0px 150px;\r\n");
      out.write("}\r\n");
      out.write("button{\r\n");
      out.write("background:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var image=['tmxmfpcld','tmxmfpcldahr','tmxmfpclddjRo','tmxmfpcldwhddkfl','tmxmfpcldwkrlwjs'];\r\n");
      out.write("var content=['기본 스트레칭','목 스트레칭','어깨 스트레칭','종아리 스트레칭','자기전 스트레칭']\r\n");
      out.write("var b=0;\r\n");
      out.write("\r\n");
      out.write("function back(){\r\n");
      out.write("\tswitch(b){\r\n");
      out.write("\tcase 1:\r\n");
      out.write("\t\tdocument.getElementById(\"content\").innerHTML = content[0];\r\n");
      out.write("\t\tdocument.getElementById(\"image\").src = \"img/\"+image[0]+\".png\";\r\n");
      out.write("\t\tb--;\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\tcase 2:\r\n");
      out.write("\t\tdocument.getElementById(\"content\").innerHTML = content[1];\r\n");
      out.write("\t\tdocument.getElementById(\"image\").src = \"img/\"+image[1]+\".png\";\r\n");
      out.write("\t\tb--;\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\tcase 3:\r\n");
      out.write("\t\tdocument.getElementById(\"content\").innerHTML = content[2];\r\n");
      out.write("\t\tdocument.getElementById(\"image\").src = \"img/\"+image[2]+\".png\";\r\n");
      out.write("\t\tb--;\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\tcase 4:\r\n");
      out.write("\t\tdocument.getElementById(\"content\").innerHTML = content[3];\r\n");
      out.write("\t\tdocument.getElementById(\"image\").src = \"img/\"+image[3]+\".png\";\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\tcase 5:\r\n");
      out.write("\t\tdocument.getElementById(\"content\").innerHTML = content[4];\r\n");
      out.write("\t\tdocument.getElementById(\"image\").src = \"img/\"+image[4]+\".png\";\r\n");
      out.write("\t\tb--;\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function next(){\r\n");
      out.write("\tswitch(b){\r\n");
      out.write("\tcase 0:\r\n");
      out.write("\t\tdocument.getElementById(\"content\").innerHTML = content[1];\r\n");
      out.write("\t\tdocument.getElementById(\"image\").src = \"img/\"+image[1]+\".png\";\r\n");
      out.write("\t\tb++;\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\tcase 1:\r\n");
      out.write("\t\tdocument.getElementById(\"content\").innerHTML = content[2];\r\n");
      out.write("\t\tdocument.getElementById(\"image\").src = \"img/\"+image[2]+\".png\";\r\n");
      out.write("\t\tb++;\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\tcase 2:\r\n");
      out.write("\t\tdocument.getElementById(\"content\").innerHTML = content[3];\r\n");
      out.write("\t\tdocument.getElementById(\"image\").src = \"img/\"+image[3]+\".png\";\r\n");
      out.write("\t\tb++;\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\tcase 3:\r\n");
      out.write("\t\tdocument.getElementById(\"content\").innerHTML = content[4];\r\n");
      out.write("\t\tdocument.getElementById(\"image\").src = \"img/\"+image[4]+\".png\";\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\tcase 4:\r\n");
      out.write("\t\tdocument.getElementById(\"content\").innerHTML = content[5];\r\n");
      out.write("\t\tdocument.getElementById(\"image\").src = \"img/\"+image[5]+\".png\";\r\n");
      out.write("\t\tb++;\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=aside>\r\n");
      out.write("<p>스트레칭</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");

String image[] = {"tmxmfpcld","tmxmfpcldahr","tmxmfpclddjRo","tmxmfpcldwhddkfl","tmxmfpcldwkrlwjs"};
String content[] = {"기본 스트레칭","목 스트레칭","어깨 스트레칭","종아리 스트레칭","자기전 스트레칭"};

      out.write('\r');
      out.write('\n');
int cnt=0; 
      out.write("\r\n");
      out.write("<div id=stretcontent>\r\n");

out.print("<h2 id=content>"+content[cnt]+ "</h2><img src= img/"+image[cnt] + ".png width=530 height=400 id=image />");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<button type=button onClick = \"back()\">이전</button>\r\n");
      out.write("<button type=button onClick = \"next()\">다음</button>\r\n");
      out.write("<p></p>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
