/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2018-12-16 07:48:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Healthcare_005fFood_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("width:1080px;\r\n");
      out.write("text-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#foodcontent{\r\n");
      out.write("width:900px;\r\n");
      out.write("height:1300px;\r\n");
      out.write("background: #FFEAEA;\r\n");
      out.write("float:right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#aside{\r\n");
      out.write("height:100px;\r\n");
      out.write("width:180px;\r\n");
      out.write("font-size:28px;\r\n");
      out.write("background: #FF9595;\r\n");
      out.write("float:left;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function next(){\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=aside>\r\n");
      out.write("<p>추천 건강푸드</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

int cnt=0;
String image[][] = {{"rnlfl","qmffnqpfl","shrck","xhakxh","qmfhzhffl","dkahsem"},
		{"todtjs","todtjs","todtjs","todtjs","todtjs","todtjs"}};
String title[] = {"귀리","블루베리","녹차","토마토","브로콜리","토마토"};
String content[] = {"효능: 심장질환예방, 콜레스테롤수치 낮춤, 다이어트,변비예방",
		"효능: 시력보호, 체내나트륨조절", 
		"효능: 항산화효과, 집중력향상", 
		"효능: 혈압 낮춤, 심혈관질환 예방",
		"효능: 비타민C 多, 피부미용에 도움",
		"효능: 알츠하이머병 예방, 배변활동 다이어트에 도움"	
};

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=foodcontent>\r\n");
      out.write("<h2>슈퍼푸드</h2>\r\n");
      out.write("<table border=0>\r\n");

for(int i=0; i<6; i=i+2){
	//out.print("<tr><td><td><img src=\"img/shrck.png\" width=400 height=280/></td><td>aa</td></tr>");
	out.print("<tr><td><img src=img/"+ image[cnt][i] +".png width=400 height=280/><h3>"+title[i]+"</h3><p>"+content[i]+
			"</p></td><td><img src=img/"+ image[cnt][i+1] +".png width=400 height=280/><h3>"+title[i+1]+"</h3><p>"+content[i+1]+"</p></td></tr>");
}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<!-- \r\n");
      out.write("<tr>\r\n");
      out.write("<td><img src=\"img/");
 out.print(image[0]); 
      out.write(".png\" width=400 height=280/>\r\n");
      out.write("<h3>귀리</h3>\r\n");
      out.write("<p>효능: 심장질환예방, 콜레스테롤수치 낮춤, 다이어트,변비예방</p>\r\n");
      out.write("</td>\r\n");
      out.write("<td><img src=\"img/qmffnqpfl.png\" width=400 height=280/>\r\n");
      out.write("<h3>블루베리</h3>\r\n");
      out.write("<p>효능: 시력보호, 체내나트륨조절</p>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><img src=\"img/shrck.png\" width=400 height=280/>\r\n");
      out.write("<h3>녹차</h3>\r\n");
      out.write("<p>효능: 항산화효과, 집중력향상</p>\r\n");
      out.write("</td>\r\n");
      out.write("<td><img src=\"img/xhakxh.png\" width=400 height=280/>\r\n");
      out.write("<h3>토마토</h3>\r\n");
      out.write("<p>효능: 혈압 낮춤, 심혈관질환 예방</p>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><img src=\"img/qmfhzhffl.png\" width=400 height=280/>\r\n");
      out.write("<h3>브로콜리</h3>\r\n");
      out.write("<p>효능: 비타민C 多, 피부미용에 도움</p>\r\n");
      out.write("</td>\r\n");
      out.write("<td><img src=\"img/dkahsem.png\" width=400 height=280/>\r\n");
      out.write("<h3>아몬드</h3>\r\n");
      out.write("<p>효능: 알츠하이머병 예방, 배변활동 다이어트에 도움</p>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<input style='float:right;' type=button value=\"다음\" onClick = \"next()\">\r\n");
      out.write(" -->\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
