/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2018-12-16 08:01:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\r\n");
      out.write("\t\t#container{\r\n");
      out.write("\t\t\twidth: 460px;\r\n");
      out.write("\t\t\theight: 710px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#container img{\r\n");
      out.write("\t\t\twidth: 150px;\r\n");
      out.write("\t\t\theight: 70px;\r\n");
      out.write("\t\t\tmargin-left: auto;\r\n");
      out.write("\t\t\tmargin-right: auto;\r\n");
      out.write("\t\t\tdisplay: block;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#name_area, #id_area, #password_area, #sex_area, #birth_area, #address_area, #phone_area, #email_area {\r\n");
      out.write("\t\t\tborder: px gray solid;\r\n");
      out.write("\t\t\tmargin: 20px 10px; \r\n");
      out.write("\t\t\theight: 40px;\r\n");
      out.write("\t\t\tfont-size: 18px;\r\n");
      out.write("\t\t\tcolor: gray;\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\t#item {\r\n");
      out.write("\t\t\tborder: px violet solid;\r\n");
      out.write("\t\t\twidth: 120px;\r\n");
      out.write("\t\t\theight: 40px;\r\n");
      out.write("\t\t\tline-height: 40px;\r\n");
      out.write("\t\t\tdisplay: inline-block;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#in_name, #in_id, #in_password, #in_sex, #in_birth, #in_address, #in_phone, #in_email {\r\n");
      out.write("\t\t\tborder: px green solid;\r\n");
      out.write("\t\t\tdisplay: inline-block;\r\n");
      out.write("\t\t\twidth: 247px;\r\n");
      out.write("\t\t\theight: 40px;\r\n");
      out.write("\t\t\tline-height: 40px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#in_sex {\r\n");
      out.write("\t\t\ttext-align: center;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#text {\r\n");
      out.write("\t\t\twidth: 244px;\r\n");
      out.write("\t\t\theight: 37px;\r\n");
      out.write("\t\t\tfont-size: 18px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#sub{\r\n");
      out.write("\t\t\ttext-align: center;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#login_button {\r\n");
      out.write("\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t\tcolor: gray;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#submit {\t\t\t\r\n");
      out.write("\t\t\tbackground-color: #FF8383;\r\n");
      out.write("\t\t\tcolor: white;\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\theight: 60px;\r\n");
      out.write("\t\t\tborder: 0px;\r\n");
      out.write("\t\t\twidth: 380px;\r\n");
      out.write("\t\t\tmargin: 10px 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("#canvas{\r\n");
      out.write("width:460px;\r\n");
      out.write("height:710px;\r\n");
      out.write("text-align:center;\r\n");
      out.write("margin:0px 0px 10px 340px;\r\n");
      out.write("border: 1px solid black;\r\n");
      out.write("float:left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=canvas>\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h1><em>Join</em></h1>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<form action=\"Join_check.jsp\" method=\"post\">\r\n");
      out.write("\t\t<div id=\"name_area\">\r\n");
      out.write("\t\t\t<div id=\"item\">이름</div>\r\n");
      out.write("\t\t\t<div id=\"in_name\"><input id=\"text\" type=\"text\" name=\"name\" required/></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"id_area\">\r\n");
      out.write("\t\t\t<div id=\"item\">아이디</div>\r\n");
      out.write("\t\t\t<div id=\"in_id\"><input id=\"text\" type=\"text\" name=\"id\" required/></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"password_area\">\r\n");
      out.write("\t\t\t<div id=\"item\">비밀번호</div>\r\n");
      out.write("\t\t\t<div id=\"in_password\"><input id=\"text\" type=\"password\" name=\"password\" required/></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"sex_area\">\r\n");
      out.write("\t\t\t<div id=\"item\">성별</div>\r\n");
      out.write("\t\t\t<div id=\"in_sex\">\r\n");
      out.write("\t\t\t\t<label><input type=\"radio\" value=\"남자\" name=\"sex\" required/>남자</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<label><input type=\"radio\" value=\"여자\" name=\"sex\" required/>여자</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"birth_area\">\r\n");
      out.write("\t\t\t<div id=item>생년월일</div>\r\n");
      out.write("\t\t\t<div id=in_birth><input id=\"text\" type=\"text\" name=\"birth\" required placeholder=\"  ex) 2018-12-08\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"address_area\">\r\n");
      out.write("\t\t\t<div id=\"item\">주소</div>\r\n");
      out.write("\t\t\t<div id=\"in_address\"><input id=\"text\" type=\"text\" name=\"address\" required/></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"phone_area\">\r\n");
      out.write("\t\t\t<div id=\"item\">핸드폰번호</div>\r\n");
      out.write("\t\t\t<div id=\"in_phone\"><input id=\"text\" type=\"tel\" name=\"phone\" required/></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"email_area\">\r\n");
      out.write("\t\t\t<div id=\"item\">E-mail주소</div>\r\n");
      out.write("\t\t\t<div id=\"in_email\"><input id=\"text\" type=\"email\" name=\"email\"/></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<input id=\"submit\" type=\"submit\" value=\"회원가입\">\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t\t<div id=\"sub\"><a id=\"login_button\" href=\"Container.jsp?selected_page=login\">로그인</a></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
