/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2018-12-16 08:01:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.Console;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t#container{\r\n");
      out.write("\t\t\twidth: 400px;\r\n");
      out.write("\t\t\theight:400px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#container img{\r\n");
      out.write("\t\t\tmargin-left: auto;\r\n");
      out.write("\t\t\tmargin-right: auto;\r\n");
      out.write("\t\t\tdisplay: block;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#id_area, #password_area {\r\n");
      out.write("\t\t\twidth: 400px;\r\n");
      out.write("\t\t\theight: 60px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t#container input {\r\n");
      out.write("\t\t\tposition: relative;\r\n");
      out.write("\t\t\tdisplay: block;\r\n");
      out.write("\t\t\twidth: 377px;\r\n");
      out.write("\t\t\theight: 34px;\r\n");
      out.write("\t\t\ttop: 10px;\r\n");
      out.write("\t\t\tbottom: 0px;\r\n");
      out.write("\t\t\tleft: 10px;\r\n");
      out.write("\t\t\tright: 0px;\r\n");
      out.write("\t\t\tfont-size: 18px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#sub{\r\n");
      out.write("\t\t\ttext-align: center;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#sign_button {\r\n");
      out.write("\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t\tcolor: gray;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#submit{\r\n");
      out.write("\t\t\tbackground-color: #FF8383;\r\n");
      out.write("\t\t\tcolor: white;\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\theight: 60px;\r\n");
      out.write("\t\t\tborder: 0px;\r\n");
      out.write("\t\t\twidth: 380px;\r\n");
      out.write("\t\t\tmargin: 10px 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("#canvas{\r\n");
      out.write("width:400px;\r\n");
      out.write("height:340px;\r\n");
      out.write("text-align:center;\r\n");
      out.write("margin:0px 0px 10px 380px;\r\n");
      out.write("border: 1px solid black;\r\n");
      out.write("float:left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

	if(session.getAttribute("id") != null)
		response.sendRedirect("Container.jsp");
	
      out.write("\r\n");
      out.write("<div id=canvas>\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<h1><em>Log in</em></h1>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<form method=\"post\" action=\"Login_check.jsp\">\r\n");
      out.write("\t\t\t<div id=\"id_area\">\r\n");
      out.write("\t\t\t\t\t<input id=\"id_field\" name=\"id\" type=\"text\" placeholder=\" 아이디\" required>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"password_area\">\r\n");
      out.write("\t\t\t\t\t<input id=\"password_field\" name=\"password\" type=\"password\" placeholder=\" 비밀번호\" required>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input id=\"submit\" type=\"submit\" value=\"로그인\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br><hr>\r\n");
      out.write("\t\t<div id=\"sub\"><a id=\"sign_button\" href=\"Container.jsp?selected_page=join\">회원가입</a></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
