/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2018-12-16 08:24:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javabean.Member;
import javabean.Access_DB;

public final class Management_005fupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction move(url){\r\n");
      out.write("\t\tlocation.href=url;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 
	request.setCharacterEncoding("EUC-KR");
	Access_DB ac = new Access_DB();
	Member mb = ac.getMember(request.getParameter("id"));
	

	if(session.getAttribute("authority") == null){
		out.println("<script>");
		out.println("alert('로그인후 이용 할 수 있습니다.')");
		out.println("location.href='Container.jsp'");
		out.println("</script>");
	}

      out.write("\r\n");
      out.write("<h2>회원정보 수정</h2>\r\n");
      out.write("\r\n");
      out.write("<table class='table table-striped'>\r\n");
      out.write("<form action=\"Management_handle.jsp\" method=\"post\">\r\n");
      out.write("\t<tr><td>아이디 : </td><td><input  class=\"form-control\" type=\"text\" id=\"id\" name=\"id\" readonly></td></tr>\r\n");
      out.write("\t<tr><td>페스워드 : </td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<td><input class=\"form-control\" type=\"text\" id=\"password\" name=\"password\" required></td></tr>\r\n");
      out.write("\t<tr><td>성별 : </td><td><label><input type=\"radio\" value=\"남자\" name=\"sex\" required/>남자</label>\r\n");
      out.write("\t\t\t<label><input type=\"radio\" value=\"여자\" name=\"sex\" required/>여자</label><br></td></tr>\r\n");
      out.write("\t<tr><td>생년월일 : </td><td><input class=\"form-control\" type=\"text\" id=\"birth\" name=\"birth\" required></td></tr>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t");
 
		if(session.getAttribute("authority") != null){
			if(session.getAttribute("authority").equals("admin"))
				out.println("<tr><td>권한 : </td><td><input class='form-control' type='text' id='authority' name='authority' required placeholder='admin, staff, member'></td></tr>");
			else
				out.println("<input type='hidden' id='authority' name='authority' required placeholder='admin, staff, member'>");
		}
	
      out.write("\r\n");
      out.write("\t<tr><td>주소 : </td><td><input class=\"form-control\" type=\"text\" id=\"address\" name=\"address\" required></td></tr>\r\n");
      out.write("\t<tr><td>핸드폰 번호 : </td><td><input class=\"form-control\" type=\"text\" id=\"phone\" name=\"phone\" required></td></tr>\r\n");
      out.write("\t<tr><td>이메일 : </td><td><input class=\"form-control\" type=\"email\" id=\"email\" name=\"email\"></td></tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<tr><td colspan='2'><input class='btn btn-primary' type=\"submit\" value=\"전송\"/><button class='btn btn-warning' onclick='move(\"Container.jsp?selected_page=management\");'>돌아가기</button></td></tr>\r\n");
      out.write("</form>\r\n");
      out.write("</table>\r\n");
      out.write("\t\r\n");
      out.write("<script>\r\n");
      out.write("\tdocument.getElementById('id').value = '");
      out.print(mb.getId() );
      out.write("';\r\n");
      out.write("\tdocument.getElementById('password').value = '");
      out.print(mb.getPassword() );
      out.write("';\r\n");
      out.write("\tdocument.getElementById('birth').value = '");
      out.print(mb.getBirth() );
      out.write("';\r\n");
      out.write("\tdocument.getElementById('authority').value = '");
      out.print(mb.getAuthority() );
      out.write("';\r\n");
      out.write("\tdocument.getElementById('address').value = '");
      out.print(mb.getAddress() );
      out.write("';\r\n");
      out.write("\tdocument.getElementById('phone').value = '");
      out.print(mb.getPhone() );
      out.write("';\r\n");
      out.write("\tdocument.getElementById('email').value = '");
      out.print(mb.getEmail() == null ? "" : mb.getEmail() );
      out.write("';\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
