/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2018-12-16 07:48:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javabean.Access_DB;
import javabean.Weather;
import java.util.ArrayList;

public final class Map_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("width:1080px;\r\n");
      out.write("text-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#Maside{\r\n");
      out.write("height:100px;\r\n");
      out.write("width:190px;\r\n");
      out.write("font-size:25px;\r\n");
      out.write("background: #FF9595;\r\n");
      out.write("float:left;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#weatherCanvas{\r\n");
      out.write("width:890px;\r\n");
      out.write("height:;\r\n");
      out.write("background: ;\r\n");
      out.write("float:right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t#lifeCanvas{\r\n");
      out.write("\t\tfloat:right;\r\n");
      out.write("\t\twidth:500px;\r\n");
      out.write("\t\theight:386px;\r\n");
      out.write("\t\tbackground-color: ;\r\n");
      out.write("\t\tmargin: 100px 0px 0px 0px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#up { \r\n");
      out.write("\t\t\tfloat: left;\r\n");
      out.write("\t\t\twidth:500px;\r\n");
      out.write("\t\t\theight: 160px;\r\n");
      out.write("\t\t\tbackground-color: ;\r\n");
      out.write("\t\t\tfloat:right;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#down {\r\n");
      out.write("\t\t\tfloat: right;\r\n");
      out.write("\t\t\twidth: 500px;\r\n");
      out.write("\t\t\theight: 170px;\r\n");
      out.write("\t\t\tbackground-color: ;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#map {\r\n");
      out.write("\t\t\tfloat: left;\r\n");
      out.write("\t\t\twidth:356px;\r\n");
      out.write("\t\t\theight: 586px;\r\n");
      out.write("\t\t\tbackground-image: url(img/korea_map.png);\r\n");
      out.write("\t\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\t\tbackground-size: contain;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#map div{\r\n");
      out.write("\t\t\tfont-family: 굴림;\r\n");
      out.write("\t\t\tfont-weight: bolder;\r\n");
      out.write("\t\t\tfloat: left;\r\n");
      out.write("\t\t\tbackground-color: black;\r\n");
      out.write("\t\t\topacity: 0.7;\r\n");
      out.write("\t\t\tborder-radius: 100px;\r\n");
      out.write("\t\t\twidth: 45px;\r\n");
      out.write("\t\t\theight: 45px;\r\n");
      out.write("\t\t\tline-height: 45px;\r\n");
      out.write("\t\t\ttext-align: center;\r\n");
      out.write("\t\t\tposition: relative;\r\n");
      out.write("\t\t\tcolor: white;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#gw {\r\n");
      out.write("\t\t\tleft: 210px;\r\n");
      out.write("\t\t\ttop: 80px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#su {\r\n");
      out.write("\t\t\tleft: 50px;\r\n");
      out.write("\t\t\ttop: 115px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#ic {\r\n");
      out.write("\t\t\tleft: -50px;\r\n");
      out.write("\t\t\ttop: 105px\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#gg {\r\n");
      out.write("\t\t\tleft: px;\r\n");
      out.write("\t\t\ttop: 140px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#cb{\r\n");
      out.write("\t\t\tleft: -20px;\r\n");
      out.write("\t\t\ttop: 190px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#cn {\r\n");
      out.write("\t\t\tleft: -175px;\r\n");
      out.write("\t\t\ttop: 210px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#se {\r\n");
      out.write("\t\t\tleft: -175px;\r\n");
      out.write("\t\t\ttop: 195px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#dj {\r\n");
      out.write("\t\t\tleft: 120px;\r\n");
      out.write("\t\t\ttop: 200px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#gb {\r\n");
      out.write("\t\t\tleft: 200px;\r\n");
      out.write("\t\t\ttop: 200px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#dg {\r\n");
      out.write("\t\t\tleft: 140px;\r\n");
      out.write("\t\t\ttop: 260px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#jb {\r\n");
      out.write("\t\t\tleft: -30;\r\n");
      out.write("\t\t\ttop: 270px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#gn {\r\n");
      out.write("\t\t\tleft: 20px;\r\n");
      out.write("\t\t\ttop: 320px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#us {\r\n");
      out.write("\t\t\tleft: 75px;\r\n");
      out.write("\t\t\ttop: 290px\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#gj {\r\n");
      out.write("\t\t\tleft: -190px;\r\n");
      out.write("\t\t\ttop: 330px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#bs {\r\n");
      out.write("\t\t\tleft: 280px;\r\n");
      out.write("\t\t\ttop: 290px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#jn {\r\n");
      out.write("\t\t\tleft: 30px;\r\n");
      out.write("\t\t\ttop: 350px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#jj {\r\n");
      out.write("\t\t\tleft: -35px;\r\n");
      out.write("\t\t\ttop: 450px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t.table_header {\r\n");
      out.write("\t\tmargin: 0px;\r\n");
      out.write("\t\tpadding: 0px;\r\n");
      out.write("\t\twidth: 60px;\r\n");
      out.write("\t\theight: 60px;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=Maside>\r\n");
      out.write("\t<p>오늘의 건강</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
 
	ArrayList<javabean.Weather> city_list = new ArrayList<javabean.Weather>();
	Access_DB ac = new Access_DB();
	String city_names[] = {"강원", "서울", "인천", "경기", "충북", "충남", "세종", "대전", "경북", "대구",
	                      "전북", "경남", "울산", "광주", "부산", "전남", "제주"};

	for(int i=0; i< city_names.length; i++){
		city_list.add(ac.getWeather(city_names[i]));
	}
	ac.closeDB();
	
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction City_list(city_name, d_weather, t_weather, rain, humidity, dust, temp, flu, \r\n");
      out.write("\t\t\t\t\t\t\te_disease, asthma, s_disease, frozen, f_poison){\r\n");
      out.write("\t\t\t\t\tthis.city_name = city_name;\r\n");
      out.write("\t\t\t\t\tthis.d_weather = d_weather;\r\n");
      out.write("\t\t\t\t\tthis.t_weather = t_weather;\r\n");
      out.write("\t\t\t\t\tthis.rain = rain;\r\n");
      out.write("\t\t\t\t\tthis.humidity = humidity;\r\n");
      out.write("\t\t\t\t\tthis.dust = dust;\r\n");
      out.write("\t\t\t\t\tthis.temp = temp;\r\n");
      out.write("\t\t\t\t\tthis.flu = flu;\r\n");
      out.write("\t\t\t\t\tthis.e_disease = e_disease;\r\n");
      out.write("\t\t\t\t\tthis.asthma = asthma;\r\n");
      out.write("\t\t\t\t\tthis.s_disease = s_disease;\r\n");
      out.write("\t\t\t\t\tthis.frozen = frozen;\r\n");
      out.write("\t\t\t\t\tthis.f_poison = f_poison;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\tvar city_list = [];\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t");
for(int i=0; i<city_names.length; i++){
      out.write("\r\n");
      out.write("\t\t\t\tcity_list.push(new City_list('");
      out.print(city_list.get(i).getCityName());
      out.write("', '");
      out.print(city_list.get(i).getdWeather());
      out.write("', '");
      out.print(city_list.get(i).gettWeahter());
      out.write("',\r\n");
      out.write("\t\t\t\t");
      out.print(city_list.get(i).getPop());
      out.write(',');
      out.write(' ');
      out.print(city_list.get(i).getHumidity());
      out.write(',');
      out.write(' ');
      out.print(city_list.get(i).getDust());
      out.write(',');
      out.write(' ');
      out.print(city_list.get(i).getSensory());
      out.write(", \r\n");
      out.write("\t\t\t\t'");
      out.print(city_list.get(i).getFlu());
      out.write("', '");
      out.print(city_list.get(i).getEyeDisease());
      out.write("', '");
      out.print(city_list.get(i).getAsthma());
      out.write("', '");
      out.print(city_list.get(i).getSkinDisease());
      out.write("',\r\n");
      out.write("\t\t\t\t");
      out.print(city_list.get(i).getFrozen());
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print(city_list.get(i).getFoodPoison());
      out.write("'));\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tfunction city_info(cityname){\r\n");
      out.write("\t\t\t\tresult = \"<table class='table' style='width: 450px;' id=top_table><tr><td colspan='6'><h2>\" + city_list[cityname].city_name + \" 지역의 날씨 정보</h2></td></tr><tr><td>\";\r\n");
      out.write("\t\t\t\tif(city_list[cityname].d_weather == \"맑음\")\r\n");
      out.write("\t\t\t\t\tresult += \"<img class='table_header' src='img/weather/sunny.png'>\";\r\n");
      out.write("\t\t\t\telse if(city_list[cityname].d_weather == \"구름조금\")\r\n");
      out.write("\t\t\t\t\tresult += \"<img class='table_header' src='img/weather/cloudy1.png'>\";\r\n");
      out.write("\t\t\t\telse if(city_list[cityname].d_weather == \"구름많음\")\r\n");
      out.write("\t\t\t\t\tresult += \"<img class='table_header' src='img/weather/cloudy2.png'>\";\r\n");
      out.write("\t\t\t\telse if(city_list[cityname].d_weather == \"흐림\")\r\n");
      out.write("\t\t\t\t\tresult += \"<img class='table_header' src='img/weather/cloudy3.png'>\";\r\n");
      out.write("\t\t\t\telse if(city_list[cityname].d_weather == \"비\")\r\n");
      out.write("\t\t\t\t\tresult += \"<img class='table_header' src='img/weather/rainy.png'>\";\r\n");
      out.write("\t\t\t\telse if(city_list[cityname].d_weather == \"눈/비\")\r\n");
      out.write("\t\t\t\t\tresult += \"<img class='table_header' src='img/weather/rainy&snowy.png'>\";\r\n");
      out.write("\t\t\t\telse if(city_list[cityname].d_weather == \"눈\")\r\n");
      out.write("\t\t\t\t\tresult += \"<img class='table_header' src='img/weather/snowy.png'>\";\r\n");
      out.write("\t\t\t\t\tresult +=\"</td><td>\";\r\n");
      out.write("\t\t\t\tif(city_list[cityname].t_weather == \"맑음\")\r\n");
      out.write("\t\t\t\t\tresult += \"<img class='table_header' src='img/weather/sunny.png'>\";\r\n");
      out.write("\t\t\t\telse if(city_list[cityname].t_weather == \"구름조금\")\r\n");
      out.write("\t\t\t\t\tresult += \"<img class='table_header' src='img/weather/cloudy1.png'>\";\r\n");
      out.write("\t\t\t\telse if(city_list[cityname].t_weather == \"구름많음\")\r\n");
      out.write("\t\t\t\t\tresult += \"<img class='table_header' src='img/weather/cloudy2.png'>\";\r\n");
      out.write("\t\t\t\telse if(city_list[cityname].t_weather == \"흐림\")\r\n");
      out.write("\t\t\t\t\tresult += \"<img class='table_header' src='img/weather/cloudy3.png'>\";\r\n");
      out.write("\t\t\t\telse if(city_list[cityname].t_weather == \"비\")\r\n");
      out.write("\t\t\t\t\tresult += \"<img class='table_header' src='img/weather/rainy.png'>\";\r\n");
      out.write("\t\t\t\telse if(city_list[cityname].t_weather == \"눈/비\")\r\n");
      out.write("\t\t\t\t\tresult += \"<img class='table_header' src='img/weather/rainy&snowy.png'>\";\r\n");
      out.write("\t\t\t\telse if(city_list[cityname].t_weather == \"눈\")\r\n");
      out.write("\t\t\t\t\tresult += \"<img class='table_header' src='img/weather/snowy.png'>\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\tresult +=\"</td><td><img class='table_header' src='img/mapTable_header/drop.png'/></td><td><img class='table_header' src='img/mapTable_header/humidity.png'/></td>\" \r\n");
      out.write("\t\t\t\t\t+ \"<td><img class='table_header' src='img/mapTable_header/sand.png'/></td><td><img class='table_header' src='img/mapTable_header/fever.png'/></td></tr>\" \r\n");
      out.write("\t\t\t\t\t+ \"<tr><td><b>오늘날씨</b></td><td><b>내일날씨</b></td><td><b>강수량</b></td><td><b>습도</b></td><td><b>미세먼지</b></td><td><b>체감온도</b></td></tr>\" \r\n");
      out.write("\t\t\t\t\t+ \"<tr><td>\" + city_list[cityname].d_weather + \"</td><td>\" + city_list[cityname].t_weather + \"</td><td>\" + city_list[cityname].rain + \"</td><td>\" + city_list[cityname].humidity + \"</td><td>\" \r\n");
      out.write("\t\t\t\t\t+ city_list[cityname].dust + \"</td><td>\" + city_list[cityname].temp + \"</td></tr>\"\r\n");
      out.write("\t\t\t\t\t+ \"<tr><td colspan='6'><h2>\" + city_list[cityname].city_name + \" 지역의 생활지수 정보</h2></td></tr><tr><td><img class='table_header' src='img/mapTable_header/sick.png'/></td><td><img class='table_header' src='img/mapTable_header/eye-disease.png'/></td><td><img class='table_header' src='img/mapTable_header/inhaler.png'/></td>\"\r\n");
      out.write("\t\t\t\t\t+ \"<td><img class='table_header' src='img/mapTable_header/allergic.png'/></td><td><img class='table_header' src='img/mapTable_header/apple.png'/></td><td><img class='table_header' src='img/mapTable_header/frozen.png'/></td></tr>\" \r\n");
      out.write("\t\t\t\t\t+ \"<tr><td><b>감기</b></td><td><b>눈병</b></td><td><b>천식</b></td><td><b>피부질환</b></td><td><b>식중독</b></td><td><b>동파</b></td></tr>\"\r\n");
      out.write("\t\t\t\t\t+ \"<tr><td>\" + city_list[cityname].flu + \"</td><td>\" + city_list[cityname].e_disease + \"</td><td>\" + city_list[cityname].asthma + \"</td><td>\" + city_list[cityname].s_disease + \"</td><td>\" + city_list[cityname].f_poison + \"</td><td>\" + city_list[cityname].frozen + \"</td></tr>\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"lifeCanvas\").innerHTML = result;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=weatherCanvas>\r\n");
      out.write("\t\t<div id=map>\r\n");
      out.write("\t\t\t<div id=gw onmouseover=\"city_info(0);\">강원</div>\r\n");
      out.write("\t\t\t<div id=su onmouseover=\"city_info(1);\">서울</div>\r\n");
      out.write("\t\t\t<div id=ic onmouseover=\"city_info(2);\">인천</div>\r\n");
      out.write("\t\t\t<div id=gg onmouseover=\"city_info(3);\">경기</div>\r\n");
      out.write("\t\t\t<div id=cb onmouseover=\"city_info(4);\">충북</div>\r\n");
      out.write("\t\t\t<div id=cn onmouseover=\"city_info(5);\">충남</div>\r\n");
      out.write("\t\t\t<div id=se onmouseover=\"city_info(6);\">세종</div>\r\n");
      out.write("\t\t\t<div id=dj onmouseover=\"city_info(7);\">대전</div>\r\n");
      out.write("\t\t\t<div id=gb onmouseover=\"city_info(8);\">경북</div>\r\n");
      out.write("\t\t\t<div id=dg onmouseover=\"city_info(9);\">대구</div>\r\n");
      out.write("\t\t\t<div id=jb onmouseover=\"city_info(10);\">전북</div>\r\n");
      out.write("\t\t\t<div id=gn onmouseover=\"city_info(11);\">경남</div>\r\n");
      out.write("\t\t\t<div id=us onmouseover=\"city_info(12);\">울산</div>\r\n");
      out.write("\t\t\t<div id=gj onmouseover=\"city_info(13);\">광주</div>\r\n");
      out.write("\t\t\t<div id=bs onmouseover=\"city_info(14);\">부산</div>\r\n");
      out.write("\t\t\t<div id=jn onmouseover=\"city_info(15);\">전남</div>\r\n");
      out.write("\t\t\t<div id=jj onmouseover=\"city_info(16);\">제주</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=lifeCanvas></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<img src=\"img/clothes.png\" width=380 height=500>\r\n");
      out.write("\t\t<img src=\"img/clothes2.png\" width=380 height=500>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tcity_info(1);\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
