/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2018-12-16 07:33:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javabean.Music;
import java.util.ArrayList;
import javabean.Access_DB;

public final class Music_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction move(url){\r\n");
      out.write("\t\tlocation.href=url;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("width:1080px;\r\n");
      out.write("text-align:center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#muaside{\r\n");
      out.write("height:100px;\r\n");
      out.write("width:160px;\r\n");
      out.write("font-size:28px;\r\n");
      out.write("background: #FF9595;\r\n");
      out.write("float:left;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#butt a{\r\n");
      out.write("font-size:20px;\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("color:black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#musicContent{\r\n");
      out.write("width:920px;\r\n");
      out.write("height:1200px;\r\n");
      out.write("float:right;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=muaside>\r\n");
      out.write("<p>추천음악<p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=musicContent>\r\n");
      out.write("<table class=\"table table-striped\">\r\n");
      out.write("<h2>Music</h2>\r\n");

	request.setCharacterEncoding("EUC-KR");
	String row = "";
	Access_DB ac = new Access_DB();
	ArrayList<Music> ml = ac.getMusics();

	int tr = (int)Math.ceil(ml.size() / 2.0);
	int page_number = 0;
	int number_of_tr = 3;
	int max_article = ml.size();
	int max_page = (int)(Math.ceil(ml.size()/6.0)) -1;
	int idx = 0;
	
	if(request.getParameter("page_number") != null){
		page_number = Integer.parseInt(request.getParameter("page_number"));
	}
	idx += page_number*6;
	for(int i=1; i<=number_of_tr; i++){
		row += "<tr><td>"+ml.get(idx).getLink() +"<br>" +ml.get(idx++).getArticle_name() + "</td>";
		if(idx==ml.size()){
			row+="<td><br></td></tr>";
			break;
		}
		row += "<td>"+ml.get(idx).getLink() +"<br>" +ml.get(idx++).getArticle_name() + "</td></tr>";
		if(idx ==ml.size())
			break;
	}
	out.println(row);


      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<div id=butt>\r\n");
      out.write("<p></p>\r\n");
      out.write("<input class=\"btn btn-danger\" type=\"button\" value=\"<<이전\" onclick='move(\"Container.jsp?selected_page=music&page_number=");
      out.print((page_number - 1 == -1 ? 0 : page_number-1) );
      out.write("\");'>\r\n");
      out.write("<input class=\"btn btn-danger\" type=\"button\" value=\"다음>>\" onclick='move(\"Container.jsp?selected_page=music&page_number=");
      out.print((page_number == max_page ? max_page : page_number + 1) );
      out.write("\");'>\r\n");
      out.write("\r\n");

	if(session.getAttribute("authority") != null){
		if(session.getAttribute("authority").toString().equals("admin")){
			out.println("<input class='btn btn-primary' type='button' value='글관리' onclick='move(\"Container.jsp?selected_page=music_manager\")'/>");
			}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
