/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2018-12-16 07:48:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Survey_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("width:1080px;\r\n");
      out.write("text-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#aside{\r\n");
      out.write("height:100px;\r\n");
      out.write("width:180px;\r\n");
      out.write("font-size:28px;\r\n");
      out.write("background: #FF9595;\r\n");
      out.write("float:left;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#surveyContent{\r\n");
      out.write("float:right;\r\n");
      out.write("width:900px;\r\n");
      out.write("heigth:500px;\r\n");
      out.write("background:#FFEAEA;\r\n");
      out.write("}\r\n");
      out.write("#surveyContent table{\r\n");
      out.write("text-align:left;\r\n");
      out.write("margin:0px 0px 0px 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	request.setCharacterEncoding("EUC-KR");
	if(session.getAttribute("id") == null){
		out.println("<script>");
		out.println("alert('로그인한 사용자만 이용할 수 있습니다.')");
		out.println("location.href ='Container.jsp'");
		out.println("</script>");
	}

      out.write("\r\n");
      out.write("<div id=aside><p style='margin:30px 0px 0px 0px;'>설문지</p>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=surveyContent>\r\n");
      out.write("<img src=\"img/survey.png\" width=80 height=80/>\r\n");
      out.write("<form action=\"Survey_handle.jsp\" method=\"post\">\r\n");

	String question[][] ={{"1. 평소 활기차게 걷기, 자전거타기, 등산 등 규칙적인 운동을 한다.", "2. 매일 30분 이상 운동을 한다.", "3. 당신의 직업은 활동적인 편이다.", "4. 당신의 직업은 활동적인 편이다.", "5. 일정 체중을 유지하려고 노력한다."},
						{"1. 매일 규칙적인 아침을 먹는다.", "2. 식사는 언제나 적당량을 먹는다.", "3. 흰 쌀밥 보다는 잡곡밥을 즐겨 먹는다.", "4. 과일을 매일 먹는다.", "5. 신선한 야채를 매일 먹는다."},
						{"1. 술을 일주일에 3번 이하로 마신다.", "2. 술을 한번 마시면 5잔 이하로 마신다.", "3. 음주 때문에 일상생활에 지장을 받은적이 없다.", "4. 술을 마신것에 대해 후회한 적이 없다.", "5. 술을 마실때 빈속에 마시지 않는다."},
						{"1. 담배를 하루에 10개비 이하로 피운다.", "2. 기상후 1시간 이내에 담배를 피우지 않는다.", "3. 금연구역에서 흡연을 참는 것이 쉽다.", "4. 담배를 습관적으로 피우지 않는다.", "5. 당장 담배가 없어도 주변사람의 담배를 빌려 피운적이 없다."},
						{"1. 최근 매우 긴장되거나 불안하지 않다.", "2. 사소한 일로 기분이 동요되지 않는다.", "3. 사소한 일에 신경질적이지 않다.", "4. 소모감, 무기력감을 느끼지 않는다.", "5. 화가 나면 자신의 감정을 억제할 수 없다."}};
	String item[] = {"운동", "식습관", "음주", "흡연", "스트레스"};


	for(int i=0; i<question.length; i++){
		String row= "<p><details><summary>" + item[i] + "</summary><table>";
		for(int j=0; j<question[i].length; j++){
			row += "<tr><td width=550>" + question[i][j] + "</td>";
			row += "<td><label><input type='radio' id='sur"+i + "_" + j + "' name='sur"+i + "_" + j + "' value='1' required>예</label>&nbsp;&nbsp;&nbsp;<label><input type='radio' id='sur"+i + "_" + j + "' name='sur"+i + "_" + j + "' value='0'>아니오</label></td></tr>";
		}
		row+="</table></details></p>";
		out.println(row);
	}

      out.write("\r\n");
      out.write("<textarea rows=\"4\" class=\"form-control\" name=\"text\" id=\"text\" style=\"margin-left: 10%; width:80%; height:100%\" placeholder=\"특이사항이나 상담받고 싶은 내용이 있다면 여기에적어주세요!! 본 사이트에 가입된 건강관리사분들이 답변을 드림니다.\"></textarea>\r\n");
      out.write("<input type=\"submit\" value=\"제출\" class=\"btn btn-success\">\r\n");
      out.write("<input type=\"reset\" value=\"초기화\" class=\"btn btn-warning\">\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
