/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2018-12-22 08:16:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.Date;
import javabean.Article;
import javabean.Access_DB;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("width:1080px;\r\n");
      out.write("text-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mainPhoto{\r\n");
      out.write("width:670px;\r\n");
      out.write("height:750px;\r\n");
      out.write("float:right;\r\n");
      out.write("text-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#notice_canvas{\r\n");
      out.write("width:400px;\r\n");
      out.write("height:500px;\r\n");
      out.write("float:left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#recomen{\r\n");
      out.write("width:300px;\r\n");
      out.write("height:250px;\r\n");
      out.write("float:left;\r\n");
      out.write("margin:0px 0px 0px 60px;\r\n");
      out.write("border: 1px solid red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#notice{\r\n");
      out.write("width:300px;\r\n");
      out.write("height:450px;\r\n");
      out.write("margin:30px 0px 10px 60px;\r\n");
      out.write("text-align:center;\r\n");
      out.write("border: 1px solid red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#mainNoticeCanvas{\r\n");
      out.write("width:540px;\r\n");
      out.write("height:500px;\r\n");
      out.write("background:red;\r\n");
      out.write("float:left;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mainMusicCanvas{\r\n");
      out.write("width:540px;\r\n");
      out.write("height:500px;\r\n");
      out.write("background:blue;\r\n");
      out.write("float:right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".scale {\r\n");
      out.write("  transform: scale(1);\r\n");
      out.write("  -webkit-transform: scale(1);\r\n");
      out.write("  -moz-transform: scale(1);\r\n");
      out.write("  -ms-transform: scale(1);\r\n");
      out.write("  -o-transform: scale(1);\r\n");
      out.write("  transition: all 0.3s ease-in-out;   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".scale:hover {\r\n");
      out.write("  transform: scale(1.2);\r\n");
      out.write("  -webkit-transform: scale(1.2);\r\n");
      out.write("  -moz-transform: scale(1.2);\r\n");
      out.write("  -ms-transform: scale(1.2);\r\n");
      out.write("  -o-transform: scale(1.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<div id=blankTemp style='width:1080px;'>&nbsp</div>\r\n");
      out.write("<div id=notice_canvas>\r\n");
      out.write("\t<div id=notice>\r\n");
      out.write("\t<h2><em>notice</em></h2>\r\n");
      out.write("\t");

		Access_DB ac = new Access_DB();
		ArrayList<Article> al = ac.getArticles(Access_DB.NOTICE);
		for(int i=0; i<al.size(); i++){
			out.println(al.get(i).getArticle_name() + "<br>");
		}
	
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=mainPhoto>\r\n");
      out.write("<h1>건강 참고</h1>\r\n");
      out.write("<a href=\"Container.jsp?selected_page=healthcare_food\"><img class=\"scale\" src=\"img/superfood.png\" width=300 height=200/></a>\r\n");
      out.write("<a href=\"Container.jsp?selected_page=music\"><img class=\"scale\" src=\"img/music.png\" width=300 height=200/></a>\r\n");
      out.write("<a href=\"Container.jsp?selected_page=survey\"><img class=\"scale\" src=\"img/survey2.png\" width=300 height=200/></a>\r\n");
      out.write("<a href=\"Container.jsp?selected_page=today\"><img class=\"scale\" src=\"img/lifeinfo.png\" width=300 height=200/></a>\r\n");
      out.write("<a href=\"\"><img class=\"scale\" src=\"img/strech.png\" width=300 height=200/></a>\r\n");
      out.write("<a href=\"\"><img class=\"scale\" src=\"img/healthnews.png\" width=300 height=200/></a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=recomen>\r\n");
      out.write("<h2>이번주 추천 음악</h2>\r\n");
      out.write("<ul>\r\n");

	al = ac.getArticles(Access_DB.MUSIC);
	for(int i=0; i<al.size(); i++){
		out.println("<li>" + al.get(i).getArticle_name() + "</li>");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<div id=mainImage>\r\n");
      out.write("<figure>\r\n");
      out.write("<img class=\"mySlides\" src=\"img/superfood.png\" width=500 height=300>\r\n");
      out.write("<img class=\"mySlides\" src=\"img/music.png\" width=500 height=300>\r\n");
      out.write("<img class=\"mySlides\" src=\"img/Mclothes.PNG\" width=500 height=300>\r\n");
      out.write("<img class=\"mySlides\" src=\"img/strech.png\" width=500 height=300>\r\n");
      out.write("<img class=\"mySlides\" src=\"img/healthnews.png\" width=500 height=300>\r\n");
      out.write("</figure>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=mainContent>\r\n");
      out.write("\r\n");
      out.write("<div id=mainNoticeCanvas>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=mainMusicCanvas>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.print(session.isNew() );
      out.write("\r\n");
      out.write("\r\n");
      out.write("세션 ID (유일한 식별자) : ");
      out.print( session.getId() );
      out.write("<br>\r\n");
 session.setMaxInactiveInterval(60*10); 
      out.write("\r\n");
      out.write("세션 MaxInactiveInterval (기본 세션 유지 시간) : ");
      out.print( session.getMaxInactiveInterval() );
      out.write("<br>\r\n");
      out.write(" \r\n");
 	
	long mseconds = session.getCreationTime();
	Date time = new Date(mseconds);

      out.write("\r\n");
      out.write("세션 CreationTime (시각으로 다시 계산) : ");
      out.print(time.toLocaleString() );
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("id : ");
      out.print(session.getAttribute("id") );
      out.write("<br>\r\n");
      out.write("password : ");
      out.print(session.getAttribute("password") );
      out.write("<br>\r\n");
      out.write("name : ");
      out.print(session.getAttribute("name") );
      out.write("<br>\r\n");
      out.write("sex : ");
      out.print(session.getAttribute("sex") );
      out.write("<br>\r\n");
      out.write("birth : ");
      out.print(session.getAttribute("birth") );
      out.write("<br>\r\n");
      out.write("authority : ");
      out.print(session.getAttribute("authority") );
      out.write("<br>\r\n");
      out.write("address : ");
      out.print(session.getAttribute("address") );
      out.write("<br>\r\n");
      out.write("phone : ");
      out.print(session.getAttribute("phone") );
      out.write("<br>\r\n");
      out.write("email : ");
      out.print(session.getAttribute("email") );
      out.write("<br>\r\n");
      out.write(" -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
